
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 17 12:39:45 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 38;
  public static final int Comillas_s = 66;
  public static final int Llave_c = 52;
  public static final int Llave_a = 51;
  public static final int Std = 65;
  public static final int Linea = 2;
  public static final int Break = 11;
  public static final int Parent_c = 50;
  public static final int Parent_a = 49;
  public static final int Corchete_c = 54;
  public static final int Op_asigResta = 39;
  public static final int Corchete_a = 53;
  public static final int T_long = 15;
  public static final int Punto = 60;
  public static final int Default = 71;
  public static final int T_char = 16;
  public static final int Op_diferente = 26;
  public static final int Op_desIzq = 45;
  public static final int For = 8;
  public static final int Void = 55;
  public static final int Else = 5;
  public static final int Resta = 21;
  public static final int Op_and = 30;
  public static final int Cin = 48;
  public static final int Suma = 20;
  public static final int Using = 67;
  public static final int ERROR = 70;
  public static final int Op_mayor = 28;
  public static final int Op_asigDiv = 40;
  public static final int Cadena = 12;
  public static final int Op_orB = 33;
  public static final int Main = 58;
  public static final int Do = 6;
  public static final int Op_or = 29;
  public static final int P_coma = 59;
  public static final int Scanf = 57;
  public static final int Case = 10;
  public static final int T_float = 17;
  public static final int Numeral = 68;
  public static final int T_byte = 18;
  public static final int Op_not = 46;
  public static final int If = 4;
  public static final int Define = 72;
  public static final int EOF = 0;
  public static final int Op_igual = 25;
  public static final int Cout = 47;
  public static final int Numero = 69;
  public static final int Division = 23;
  public static final int Op_desDer = 44;
  public static final int Op_asigModulo = 43;
  public static final int Namespace = 63;
  public static final int error = 1;
  public static final int Op_menor = 27;
  public static final int Comillas = 3;
  public static final int Op_menorE = 31;
  public static final int Op_mayorE = 32;
  public static final int Iostream = 64;
  public static final int Identificador = 61;
  public static final int Op_asigMult = 41;
  public static final int Op_incremento = 37;
  public static final int Op_boolFalse = 35;
  public static final int Include = 73;
  public static final int DPuntos = 62;
  public static final int Modulo = 24;
  public static final int T_int = 13;
  public static final int Printf = 56;
  public static final int T_double = 14;
  public static final int Op_andB = 34;
  public static final int Op_boolTrue = 36;
  public static final int Op_asigSuma = 42;
  public static final int Igual = 19;
  public static final int While = 7;
  public static final int Multiplicacion = 22;
  public static final int Switch = 9;
}

