
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 03 00:24:28 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 38;
  public static final int Op_mayor = 26;
  public static final int Op_asigSuma = 42;
  public static final int Llave_c = 49;
  public static final int Llave_a = 48;
  public static final int If = 4;
  public static final int T_char = 15;
  public static final int Void = 52;
  public static final int Default = 61;
  public static final int Op_boolFalse = 34;
  public static final int Else = 5;
  public static final int Op_mayorE = 30;
  public static final int Corchete_c = 51;
  public static final int Corchete_a = 50;
  public static final int Op_asigDiv = 40;
  public static final int Punto = 57;
  public static final int Parent_c = 47;
  public static final int Op_orB = 32;
  public static final int Parent_a = 46;
  public static final int Op_desIzq = 45;
  public static final int T_double = 13;
  public static final int While = 7;
  public static final int Division = 22;
  public static final int Int = 9;
  public static final int Cadena = 11;
  public static final int For = 8;
  public static final int P_coma = 56;
  public static final int EOF = 0;
  public static final int Printf = 53;
  public static final int error = 1;
  public static final int Switch = 10;
  public static final int Linea = 2;
  public static final int Op_asigResto = 43;
  public static final int Op_atribucion = 36;
  public static final int ERROR = 60;
  public static final int Do = 6;
  public static final int T_byte = 17;
  public static final int Op_menorE = 29;
  public static final int Op_igual = 23;
  public static final int Op_asigMult = 41;
  public static final int Scanf = 54;
  public static final int T_int = 12;
  public static final int Op_asigResta = 39;
  public static final int Op_andB = 33;
  public static final int Identificador = 58;
  public static final int Op_desDer = 44;
  public static final int Resta = 20;
  public static final int T_long = 14;
  public static final int Multiplicacion = 21;
  public static final int Op_incremento = 37;
  public static final int Numero = 59;
  public static final int Op_or = 27;
  public static final int Suma = 19;
  public static final int Op_boolTrue = 35;
  public static final int Op_not = 31;
  public static final int Op_and = 28;
  public static final int T_float = 16;
  public static final int Main = 55;
  public static final int Op_menor = 25;
  public static final int Igual = 18;
  public static final int Op_diferente = 24;
  public static final int Comillas = 3;
}

